### ISSUE TITLE
WebRTC goes to new window instead of displaying card

### ISSUE THREAD

**Issue by tevko** [tevko/getCaniuse#1]

**Comment by tevko** [comment]
AS it turns out, webrtc is also referred to as rtcpeerconnection. In this case it's probably okay to leave the behavior as is.

**Comment by impressivewebs** [comment]
I know this was already closed, but I'm wondering if maybe it would be better to use a `data-*` attribute to hold the official CIU name, instead of being forced to refer to it using the exact term that CIU's JSON data uses. Of course, then the developer would have to know the exact term when writing the custom element.

But this would solve the problem of doing something like `<get-caniuse>CSS gradients</get-caniuse> and getting the same behaviour as described in this issue (opens in a new window, doing a CIU search, rather than doing the JS popup thing.)

Just my two cents.
